## Print Statements

In [2]:
print("Hello World")
num = 9
print("The Value of num is", num)

print(1,2,3,4,5,6,7,8,9, sep='*')
print(1,2,3,4,5,6,7,8,9, sep='#', end='&')



Hello World
The Value of num is 9
1*2*3*4*5*6*7*8*9
1#2#3#4#5#6#7#8#9&

## Variables

In [6]:
var1 = 9
var2 =9.99
var3 = "Nine"
print(var1, var2, var3)

var1 = var2 = var3 = "Nine"
print(var1, var2, var3)

var1, var2, var3 = 9, 9.99, "Nine"
print(var1, var2, var3)

9 9.99 Nine
Nine Nine Nine
9 9.99 Nine


## Input

In [7]:
inputInteger = int(input("Enter an Integer: "))
inputFloat = float(input("Enter a Float: "))
inputString = input("Enter a String: ")

print("Integer: ", inputInteger)
print("Float: ", inputFloat)
print("String: ", inputString)

Integer:  9
Float:  9.09
String:  Nine


## Datatypes

In [25]:
# 1. Numeric
print("Numeric\n")
num = 9
print("The type of num is", type(num))

num = 9.99
print("The type of num is", type(num))

num = 9+9j
print("The type of num is", type(num))

# 2. Sequence Type
# 2.1 String
print("\nString\n")
str = "Hello World"
print("The type of str is", type(str))
print("The length of str is", len(str))
print("First Character of str is", str[0])
print("Last Character of str is", str[-1])
print("Substring of str is", str[2:5])
print("Print Twics", str*2)
print("Concatenate", str + "!")

# 2.2 List
print("\nList\n")
list = [1,2,3,4,5]
print("The type of list is", type(list))
print("The length of list is", len(list))
print("First Element of list is", list[0])
list[0] = 9
print("First Element of list is", list[0])
list.append(6)
print("List after append", list)
list.remove(6)
print("List after remove", list)

tempList = ['a','b','c']
newList = list + tempList
print("New List", newList)

# 2.3 Tuple
print("\nTuple\n")
tuple = (1,2,3,4,5)
print("The type of tuple is", type(tuple))
print("The length of tuple is", len(tuple))
print("First Element of tuple is", tuple[0])
# tuple[0] = 9 # error

# 2.4 Dictionary
print("\nDictionary\n")
dict = {1:'a', 2:'b', 3:'c'}
print("The type of dict is", type(dict))
print("The length of dict is", len(dict))
print("Dictionary", dict)
print("Value of key 1 is", dict[1])

for key in dict:
    print("Key", key, "Value", dict[key])


Numeric

The type of num is <class 'int'>
The type of num is <class 'float'>
The type of num is <class 'complex'>

String

The type of str is <class 'str'>
The length of str is 11
First Character of str is H
Last Character of str is d
Substring of str is llo
Print Twics Hello WorldHello World
Concatenate Hello World!

List

The type of list is <class 'list'>
The length of list is 5
First Element of list is 1
First Element of list is 9
List after append [9, 2, 3, 4, 5, 6]
List after remove [9, 2, 3, 4, 5]
New List [9, 2, 3, 4, 5, 'a', 'b', 'c']

Tuple

The type of tuple is <class 'tuple'>
The length of tuple is 5
First Element of tuple is 1

Dictionary

The type of dict is <class 'dict'>
The length of dict is 3
Dictionary {1: 'a', 2: 'b', 3: 'c'}
Value of key 1 is a
Key 1 Value a
Key 2 Value b
Key 3 Value c


## Bulit-in Functions

In [28]:
print("Sum of Array", sum([1,2,3,4,5]))
print("Minimum of Array", min([1,2,3,4,5]))
print("Maximum of Array", max([1,2,3,4,5]))
print("Sorted Array", sorted([5,4,3,2,1]))
print("Length of Array", len([1,2,3,4,5]))
print("Absolute Value", abs(-9))
print("Power", pow(2,3))
print("Round", round(9.99))

import math
print("Square Root", math.sqrt(9))
print("Log", math.log(9))


Sum of Array 15
Minimum of Array 1
Maximum of Array 5
Sorted Array [1, 2, 3, 4, 5]
Length of Array 5
Absolute Value 9
Power 8
Round 10
Square Root 3.0
Log 2.1972245773362196


## Functions

In [34]:
def hello():
    print("Hello World")    

hello()

def add(a,b):
    return a+b

print("Sum", add(9,9))

Hello World
Sum 18


## Numpy

In [65]:
import numpy as np

a = np.array([1,2,3,4,5])
b = np.array([6,7,8,9,10])

print("Regular Matrix Addition", a+b)
print("Broadcasting Matrix Addition", a+10)

# 2d matrix
a = np.array([[1,2,3],[4,5,6]])
b = np.array([[7,8,9],[10,11,12]])

print("Regular Matrix Addition", a+b)

a = np.ones((4,4))
print("Matrix of Ones\n", a)
print("Matrix of Zeros\n", np.zeros((3,3)))
print("Identity Matrix\n", np.eye(3))

print("Second Row of b\n", b[1,:])
print("Second Column of b\n", b[:,1])


# MAtrix Properties
print("Shape of b", b.shape)
print("Number of Elements in b", b.size)
print("Number of Dimensions in b", b.ndim)
print("Average of b", np.mean(b))
print("Maximum Element of b", np.max(b))
print("Diagonal of b", np.diag(b))


# Matrix Operations
print("Transpose of b\n", b.T)
print("Flatten of b\n", b.flatten())
print("Reshape of b\n", b.reshape(3,2))


a = np.array([[1,2],[3,4]])
b = np.array([[5,6],[7,8]])

print("Matrix Addition\n", np.add(a,b))
print("Matrix Multiplication\n", np.multiply(a,b))

Regular Matrix Addition [ 7  9 11 13 15]
Broadcasting Matrix Addition [11 12 13 14 15]
Regular Matrix Addition [[ 8 10 12]
 [14 16 18]]
Matrix of Ones
 [[1. 1. 1. 1.]
 [1. 1. 1. 1.]
 [1. 1. 1. 1.]
 [1. 1. 1. 1.]]
Matrix of Zeros
 [[0. 0. 0.]
 [0. 0. 0.]
 [0. 0. 0.]]
Identity Matrix
 [[1. 0. 0.]
 [0. 1. 0.]
 [0. 0. 1.]]
Second Row of b
 [10 11 12]
Second Column of b
 [ 8 11]
Shape of b (2, 3)
Number of Elements in b 6
Number of Dimensions in b 2
Average of b 9.5
Maximum Element of b 12
Diagonal of b [ 7 11]
Transpose of b
 [[ 7 10]
 [ 8 11]
 [ 9 12]]
Flatten of b
 [ 7  8  9 10 11 12]
Reshape of b
 [[ 7  8]
 [ 9 10]
 [11 12]]
Matrix Addition
 [[ 6  8]
 [10 12]]
Matrix Multiplication
 [[ 5 12]
 [21 32]]
